CREATE TABLE vendedor( 
id INT NOT NULL AUTO_INCREMENT,
clientevenda VARCHAR(70) NOT NULL, 
idade INT NOT NULL, 
data_nasc VARCHAR(70) NOT NULL,
data_contr  VARCHAR(70) NOT NULL,
sal VARCHAR(70) NOT NULL,
PRIMARY KEY(id));